spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/warden?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: sayhellO00
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 20000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      remove-abandoned: true
      remove-abandoned-timeout-millis: 7200000
      validation-query: SELECT 1
      validation-query-timeout: 100
      # 验证连接的有效性
      test-while-idle: true
      # 获取连接时候验证，会影响性能
      test-on-borrow: false
      # 在连接归还到连接池时是否测试该连接
      test-on-return: false
      # 空闲连接回收的时间间隔，与 test-while-idle 一起使用，
      time-between-eviction-runs-millis: 60000
      # 连接池空闲连接的有效时间
      min-evictable-idle-time-millis: 30000
      # 配置监控统计拦截的 filters，去掉后监控界面 sql 无法统计，wall 用于防火墙
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开 mergeSql 功能；慢 SQL 记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jpa:
    show-sql: false
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8080
  servlet:
    context-path: /warden

#logging:
#  config: logback-spring.xml